### ISSUE TITLE
Suggestion of Naming Commit 

### ISSUE THREAD

**Issue by 1chooo** [wangtyphoon/weather_hackson_visual#2]
### Descriptions
Upon reviewing the commit history of this repository, I noticed certain descriptions that make it difficult to track the version control. Consequently, I have some suggestions to improve the situation. After completing our tasks, when we are ready to commit and push the changes to GitHub, we should adhere to the following tips for naming our commits:

1. Keep descriptions concise.
2. Utilize verb + "ing" or noun forms to name commits.
3. Include information relevant to the work being done.

By following these guidelines, we can ensure better clarity and organization in our commit history.

BR,
@1chooo

**Comment by wangtyphoon** [comment]
Thenk you for your advice,I will fix the issue in the future.

Hugo ChunHo Lin ***@***.***> 於 2023年7月3日 週一 17:44 寫道：
